
name: bot-taks-scheduler
on:
  schedule:
  - cron: '0 6 * * *' #06 Hour UTC = 13 Hour GMT+7
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest    
    steps:
      - name: Check Repo
        uses: actions/checkout@v2.3.4        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Set TimeZone for JS environment
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Bangkok"
      - name: Install Node.js dependencies
        run: npm install      
      - name: Setup Python Environment
        uses: actions/setup-python@v2.2.1
      - name: Get Latest Data From The Government Database
        working-directory: bot_jobs
        run: node get_data.js
      - name: Get vaccination datasets
        working-directory: bot_jobs/vaccination
        run: |
          node get-national-data.js
          node fetch-MOPH-dashboard.js
      - name: Process Data Received (Infection data)
        working-directory: bot_jobs
        run: node process_data.js
      - name: Build Province Graphs in svg using Python
        working-directory: bot_jobs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python build.py
      
      #- name: Build Vaccination graphs in svg using python
      #  working-directory: bot_jobs/vaccination
      #  run: python build.py
      - name: Commit Changes to Git Repo
        run: |
          git config --global user.name "porames"
          git config --global user.email "porames@users.noreply.github.com"
          git add -A
          git commit -m "[Bot 🤖] build data from today's dataset $(date)"
          git push
